frame_id:
  fixed: $(arg robot_namespace)/map
  base: $(arg robot_namespace)/base_link
  imu: $(arg robot_namespace)/vn100
  odometry: $(arg robot_namespace)/base_link_blam_odometry
  artifacts_in_global: true
