include:
  - project: rollocopter/core/core_environment
    file: shared/ci/default-ci.yml

catkin_lint:
  script:
    # Override default lint setting
    - catkin lint catkin_ws/src/${CI_PROJECT_NAME} --color=always --explain
        --ignore cmake_build_type
        --ignore unconfigured_system_depend