#Load and restart deltas
load_graph_x: 0.0 
load_graph_y: 0.0 
load_graph_z: 0.0 
load_graph_roll: 0.0 
load_graph_pitch: 0.0 
load_graph_yaw: 0.0 

restart_x: 0.0 
restart_y: 0.0 
restart_z: 0.0 
restart_roll: 0.0 
restart_pitch: 0.0 
restart_yaw: 0.0 