robot: 
  # Toggle loop closures on or off. Setting this to off will increase run-time
  # Solver used in backend. 1 for LM, 2 for GN
  solver: 1

  # Toggle outlier rejection
  b_use_outlier_rejection: true

  # GNC confidence threshold 
  gnc_alpha: 0

  # outlier rejection thresholds (distances)
  translation_check_threshold: 0.01 # 1 centimeter
  rotation_check_threshold: 0.005 # ~0.3 degrees
  # TODO make these dynamic with the translation threshold for nodes

base:
  # Toggle loop closures on or off. Setting this to off will increase run-time
  # Solver used in backend. 1 for LM, 2 for GN
  solver: 1

  # Toggle outlier rejection
  b_use_outlier_rejection: true

  # GNC confidence threshold 
  gnc_alpha: 0.9999999999

  # outlier rejection thresholds (distances)
  translation_check_threshold: 0.5 # 50 centimeters
  rotation_check_threshold: 0.1 # ~6 degrees
  # TODO make these dynamic with the translation threshold for nodes
