###
# PARAMETERS FOR OUTLIER REJECTION AND SANITY CHECKS
###
# outlier rejection thresholds (distances)
translation_check_threshold: 0.1 # 10 centimeters
rotation_check_threshold: 0.01 # ~0.57 degrees
# TODO make these dynamic with the translation threshold for nodes

########################################
# Use zip file for backup or from memory?
load_graph_from_zip_file: false

# Sanity check thresholds
translational_sanity_check_lc: 100
translational_sanity_check_odom: 3
