########################################
# PARAMETERS FOR UWB
########################################

#---------------------------------------
# UWB Data Collection & Handling
# --------------------------------------

# Flag to activate UWB data outlier rejection
b_use_uwb_outlier_rejection: true

# Flag to decide whether to show uwb data or not (for debugging)
b_use_display_uwb_data: true

b_uwb_test_data_collection: false

# Pose key number threshold to wait for accepting UWB signal
uwb_first_key_threshold: 3

# UWB range measurement noise (standard deviation)
uwb_range_measurement_error: 10.0

# Number of range measurement which is necessary to add a new UWB factor
uwb_skip_measurement_number: 5

# Pose key number for checking whether there are enough number of range measurements or not
uwb_update_key_number: 5

# Rquired number of pose keys linked with UWB range measurement
uwb_required_key_number_first: 5
uwb_required_key_number_not_first: 3

#---------------------------------------
# Adding Range Factors
# --------------------------------------

# How to add range factors into a pose graph
# 0 - Add limited number of range factors decided by "uwb_number_added_rangefactor_first" and "uwb_number_added_rangefactor_not_first"
# 1 - Add all range measurement whose value is between "uwb_minimum_range_threshold" and "uwb_maximum_range_threshold"
uwb_adding_range_option: 1

# Optimizer selection for UWB factors: 0 - ISAM2, 1 - LM
uwb_factor_optimizer: 1

# Number of range factors added at the first observation
uwb_number_added_rangefactor_first: 3

# Number of range factors added against an existing UWB key in the pose graph
uwb_number_added_rangefactor_not_first: 3

# Range added into the pose graph should be longer than the following value
uwb_minimum_range_threshold: 3.0

# Range added into the pose graph should be shorter than the following value
uwb_maximum_range_threshold: 10.0

#---------------------------------------
# Drop UWB
# --------------------------------------

b_uwb_add_betweenfactor: true

uwb_dropped_position:
  # x: -0.94
  x: -0.50
  y: 0.0
  z: -0.55
