# When searching through old poses for loop closures, only consider old poses
# that are within this distance of the current pose.
# (for visualisation only)
proximity_threshold: 5


# Option for whether or not to subscribe to the reconciled artifacts 
b_use_base_reconciliation: true