# Calibration value for left
calibration_left_x: 0.1
calibration_left_y: 0.1 
calibration_left_z: 0.1

# Calibration value for right
calibration_right_x: 0.1
calibration_right_y: 0.1
calibration_right_z: 0.1

# Calibration value for distal
distal_x: 0.1
distal_y: 0.1
distal_z: 0.1