# Thresholds to set a new node
translation_threshold: 1.0

# Point cloud storing parameters
keyed_scan_time_diff_limit: 5.0
pc_buffer_size_limit: 50

# Timestamp threshold 
ts_threshold: 0.05

# Buffer size limits
max_buffer_size: 6000

# Debugging message for point cloud buffer handling
b_debug_pointcloud_buffer: false

subscriptions: 
  b_register_lidar_sub: true
  b_register_visual_sub: false
  b_register_wheel_sub: false
