# Thresholds to set a new node
translation_threshold: 1.0

# Point cloud storing parameters
keyed_scan_time_diff_limit: 0.5
pc_buffer_size_limit: 10

# Timestamp threshold 
ts_threshold: 5.0

# Transformation between imu_frame and base_frame 
base: $(arg robot_namespace)/base_link
imu: $(arg robot_namespace)/vn100
