#######################################
# Higher level settings for LAMP for development purposes
#######################################

# Use fixed covariances, rather than computed
b_use_fixed_covariances: true

# Flag for whether or not to do loop closure with the artifacts
use_artifact_loop_closure: false

# Flag for whether of not to use uwb data for range-based loop closure
b_use_uwb: false

# Flag for whether of not to use imu data for roll and pitch constraints
b_add_imu_factors: true
factors_per_opt: 1

# Artifacts in global frame
b_artifacts_in_global: false

# Threshold for time to be matched 
time_threshold: 10.0


#######################################
# Robot LAMP settings
#######################################
robot: 

  # Turn laser loop closures on or off
  b_find_laser_loop_closures: false


#######################################
# Base station LAMP settings
#######################################
base: 
  # Turn laser loop closures on or off
  b_find_laser_loop_closures: false

  # if true, optimize every time a new artifact edge is received
  # if false, currently won't optimize for artifact loop closures
  b_optimize_on_artifacts: false 

