#######################################
# Higher level settings for LAMP for development purposes
#######################################

# Use fixed covariances, rather than computed
b_use_fixed_covariances: true

# Flag for whether or not to do loop closure with the artifacts
use_artifact_loop_closure: false