#######################################
# Initial sigmas for the starting pose
#######################################

# Noise parameters for odometry
init:
  position_sigma:
    x:      0.016
    y:      0.016
    z:      0.016
  orientation_sigma:
    roll:   0.041
    pitch:  0.041
    yaw:    0.041
