#######################################
# Placeholder precisions for the pose-graph - to use before having computed covariances
#######################################

# Noise parameters for odometry
attitude_sigma: 0.316
position_sigma: 0.6324

# Noise parameters (as variances) for Laser loop closure
laser_lc_rot_sigma: 0.01 #0.316 # default 0.01
laser_lc_trans_sigma: 0.01 #0.6324 # default 0.04

# Noise parameters (as precisions) for artifacts
artifact_rot_precision: 0.0
artifact_trans_precision: 0.005 #0.005

# Noise parameters (as precisions) for fiducials
fiducial_rot_precision: 0.0
fiducial_trans_precision: 0.0

# Noise parameters (as precisions) for point estimation service (survey tool integration)
point_estimate_precision: 25.0
