filtering:

  # VOXEL GRID FILTER 
  grid_filter: true
  # Resolution of voxel grid filter
  grid_res: 0.3

  # RANDOM DOWNSAMPLE FILTER
  random_filter: true
  # Percentage of points to discard. Must be between 0.0 and 1.0.
  decimate_percentage: 0.90
  decimate_percentage_open_space: 0.97

  # ADAPTIVE FILTER 
  adaptive_filter: false
  # Number of points to target for adaptive filter
  adaptive_target: 3000