#############################################
# PARAMETERS FOR LASER LOOP CLOSURES (ROBOT)
#############################################

robot: 

  #--------------------------------------------------------------------------------
  #### Loop closure generation 
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  # Translation threshold for new nodes to compute values for loop closure checking
  translation_threshold_nodes: 1.0

  # When searching through old poses for loop closures, only consider old poses
  # that are within this distance of the current pose.
  proximity_threshold: 5

  # Don't attempt loop closures with poses in the graph that were collected within
  # this translational distance (m) from the current pose.
  distance_to_skip_recent_poses: 15 #10 # 200

  #--------------------------------------------------------------------------------
  #### Loop closure prioritization
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  # Loop closure prioritization method { GENERIC, OBSERVABILITY}
  prioritization_method: 0

  #--------------------------------------------------------------------------------
  # Generic prioritization loop closure (by order recieved)
  #--------------------------------------------------------------------------------
  gen_prioritization:
    min_observability: 100
    normals_search_radius: 1.0
    choose_best: true # send only the best candidate for geometric verification
    threads: 4

  #--------------------------------------------------------------------------------
  # Observability prioritization loop closure
  #--------------------------------------------------------------------------------
  obs_prioritization:
    publish_n_best: 10
    min_observability: 0.2
    horizon: 120
    normals_search_radius: 1.0
    therads: 4

  #--------------------------------------------------------------------------------
  #### Loop closure computation
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  # Initialization method { IDENTITY, ODOMETRY, ODOM_ROTATION, FEATURES, TEASER }
  icp_initialization_method: 3

  # ICP covariance calculation method { POINT2POINT, POINT2PLANE }
  icp_covariance_calculation: 1

  # To compute a loop closure we perform ICP between the current scan and laser
  # scans captured from nearby poses. In order to be considered a loop closure,
  # the ICP "fitness score" must be less than this number.
  max_tolerable_fitness: 0.4 #0.04

  # How long to "wait" for keyed scans 
  keyed_scans_max_delay: 0.1

  icp_lc:
    # Stop ICP if the transformation from the last iteration was this small.
    tf_epsilon: 0.0000000001

    # During ICP, two points won't be considered a correspondence if they are at
    # least this far from one another.
    corr_dist: 0.1

    # Iterate ICP this many times.
    iterations: 5 # Default from original branch is 20: 

    # Number of threads for multithreaded GICP
    threads: 4
  
  #--------------------------------------------------------------------------------
  # SAC-IA Settings for feature-based initialization
  #--------------------------------------------------------------------------------

  sac_ia:
    # Iterate SAC-IA this many times.
    iterations: 10

    # Number of previous scans to accumulate for target pointcloud
    # 0 means no accumulation
    num_prev_scans: 2
    num_next_scans: 2
    
    # Radii of area to consider when computing normals and features
    normals_radius: 1.0
    features_radius: 2.0

    # If SAC fitness score is more than the following value, it will be rejected
    fitness_score_threshold: 1.2

  #--------------------------------------------------------------------------------
  # TEASER Settings for feature-based initialization
  #--------------------------------------------------------------------------------
  
  TEASERPP:

    num_inlier_threshold: 5
    rotation_cost_threshold: 1.0 # Default value in TEASER++: 0.005
    rotation_max_iterations: 100
    noise_bound: 0.05
    # For finding FPFH correspondences
    TEASER_FPFH_normals_radius: 1.5
    TEASER_FPFH_features_radius: 2.0

  #--------------------------------------------------------------------------------
  # Harris keypoints Settings 
  #--------------------------------------------------------------------------------
  
  harris3D:
    # Set the threshold value to filter out weak corners. This is only evaluated if non maxima suppression is turned on.
    harris_threshold: 0.000000005

    # Whether non maxima suppression should be applied or the response for each point should be returned
    harris_suppression: true

    # the radius for normal estimation as well as for non maxima suppression
    harris_radius: 0.1

    # Whether the detected key points should be refined or not
    harris_refine: false

    # Response type: {HARRIS = 1, NOBLE, LOWE, TOMASI, CURVATURE}
    harris_response: 1

#############################################
# PARAMETERS FOR LASER LOOP CLOSURES (BASE)
#############################################

base: 
  #--------------------------------------------------------------------------------
  #### Loop closure generation 
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  # Translation threshold for new nodes to compute values for loop closure checking
  translation_threshold_nodes: 1.0

  # When searching through old poses for loop closures, only consider old poses
  # that are within this distance of the current pose.
  proximity_threshold: 15

  # Don't attempt loop closures with poses in the graph that were collected within
  # this translational distance (m) from the current pose.
  distance_to_skip_recent_poses: 10 #10 # 200

  #--------------------------------------------------------------------------------
  #### Loop closure prioritization
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  # Loop closure prioritization method { GENERIC, OBSERVABILITY}
  prioritization_method: 1

  #--------------------------------------------------------------------------------
  # Generic prioritization loop closure (by order recieved)
  #--------------------------------------------------------------------------------
  gen_prioritization:
    min_observability: 100
    normals_search_radius: 1.0
    choose_best: false # send only the best candidate for geometric verification
    threads: 8

  #--------------------------------------------------------------------------------
  # Observability prioritization loop closure
  #--------------------------------------------------------------------------------
  obs_prioritization:
    publish_n_best: 30
    min_observability: 0.2 # normalized from 0 to 1
    horizon: 300
    normals_search_radius: 1.0
    threads: 8

  #--------------------------------------------------------------------------------
  #### Loop closure computation
  #--------------------------------------------------------------------------------
  #--------------------------------------------------------------------------------
  # Initialization method { IDENTITY, ODOMETRY, ODOM_ROTATION, FEATURES, TEASER }
  icp_initialization_method: 3

  # ICP covariance calculation method { POINT2POINT, POINT2PLANE }
  icp_covariance_calculation: 1

  # To compute a loop closure we perform ICP between the current scan and laser
  # scans captured from nearby poses. In order to be considered a loop closure,
  # the ICP "fitness score" must be less than this number.
  max_tolerable_fitness: 0.8 #0.04

  # How long to "wait" for keyed scans 
  keyed_scans_max_delay: 60.0

  icp_lc:
    # Stop ICP if the transformation from the last iteration was this small.
    tf_epsilon: 0.0000000001

    # During ICP, two points won't be considered a correspondence if they are at
    # least this far from one another.
    corr_dist: 0.5

    # Iterate ICP this many times.
    # Check this
    iterations: 10 #was 5 # Default from original branch is 20: 
                  # For ground truth generation set it to a high number (100)
    
    # Number of threads for multithreaded GICP
    threads: 8

  #--------------------------------------------------------------------------------
  # SAC-IA Settings for feature-based initialization
  #--------------------------------------------------------------------------------

  sac_ia:
    # Iterate SAC-IA this many times.
    iterations: 10

    # Number of previous scans to accumulate for target pointcloud
    # 0 means no accumulation
    num_prev_scans: 2
    num_next_scans: 2
    
    # Radii of area to consider when computing normals and features
    normals_radius: 1.0
    features_radius: 2.0

    # If SAC fitness score is more than the following value, it will be rejected
    fitness_score_threshold: 8.0

  #--------------------------------------------------------------------------------
  # TEASER Settings for feature-based initialization
  #--------------------------------------------------------------------------------
  
  TEASERPP:

    num_inlier_threshold: 5
    rotation_cost_threshold: 1.0 # Default value in TEASER++: 0.005
    rotation_max_iterations: 100
    noise_bound: 0.05
    # For finding FPFH correspondences
    TEASER_FPFH_normals_radius: 1.5
    TEASER_FPFH_features_radius: 2.0

  #--------------------------------------------------------------------------------
  # Harris keypoints Settings 
  #--------------------------------------------------------------------------------
  
  harris3D:
    # Set the threshold value to filter out weak corners. This is only evaluated if non maxima suppression is turned on.
    harris_threshold: 0.000000005

    # Whether non maxima suppression should be applied or the response for each point should be returned
    harris_suppression: true

    # the radius for normal estimation as well as for non maxima suppression
    harris_radius: 0.1

    # Whether the detected key points should be refined or not
    harris_refine: false

    # Response type: {HARRIS = 1, NOBLE, LOWE, TOMASI, CURVATURE}
    harris_response: 1