#############################################
# PARAMETERS FOR LASER LOOP CLOSURES (ROBOT)
#############################################

robot: 

  # Initialization method { IDENTITY, ODOMETRY, ODOM_ROTATION, FEATURES }
  icp_initialization_method: 3

  # Translation threshold for new nodes to compute values for loop closure checking
  translation_threshold_nodes: 1.0

  # When searching through old poses for loop closures, only consider old poses
  # that are within this distance of the current pose.
  proximity_threshold: 10

  # To compute a loop closure we perform ICP between the current scan and laser
  # scans captured from nearby poses. In order to be considered a loop closure,
  # the ICP "fitness score" must be less than this number.
  max_tolerable_fitness: 0.10

  # Don't attempt loop closures with poses in the graph that were collected within
  # this translational distance (m) from the current pose.
  distance_to_skip_recent_poses: 10 #10 # 200

  # If a loop has recently been closed, don't close a new one for at least this
  # amount of translational distance (m).
  distance_before_reclosing: 5 #10

  # If a batchloop has recently been closed, don't close a new one for at least this
  # amount of translational distance (m).
  distance_before_batch_reclosing: 10 #3

  # if a loop closure is found but the angle is larger than this, reject it
  max_rotation_deg: 50

  #--------------------------------------------------------------------------------
  # ICP Settings for laser loop closure
  #--------------------------------------------------------------------------------

  icp_lc:
    # Stop ICP if the transformation from the last iteration was this small.
    tf_epsilon: 0.0000000001

    # During ICP, two points won't be considered a correspondence if they are at
    # least this far from one another.
    corr_dist: 5.0

    # Iterate ICP this many times.
    iterations: 5 # Default from original branch is 20: 

    # Number of threads for multithreaded GICP
    threads: 1
  
  #--------------------------------------------------------------------------------
  # SAC-IA Settings for feature-based initialization
  #--------------------------------------------------------------------------------

  sac_ia:
    # Iterate SAC-IA this many times.
    iterations: 10

    # Number of previous and next scans to accumulate for target pointcloud
    # 0 means no accumulation
    num_prev_scans: 2
    num_next_scans: 2

    # Radii of area to consider when computing normals and features
    normals_radius: 1.0
    features_radius: 2.0

    # If SAC fitness score is more than the following value, it will be rejected
    fitness_score_threshold: 0.30

  harris3D:
    harris_threshold_: 1
    harris_suppression: true
    harris_radius: 2.0
    harris_refine: true
    harris_response: 1

#############################################
# PARAMETERS FOR LASER LOOP CLOSURES (BASE)
#############################################

base: 
  # Initialization method { IDENTITY, ODOMETRY, ODOM_ROTATION, FEATURES }
  icp_initialization_method: 3

  # Translation threshold for new nodes to compute values for loop closure checking
  translation_threshold_nodes: 1.0

  # When searching through old poses for loop closures, only consider old poses
  # that are within this distance of the current pose.
  proximity_threshold: 5

  # To compute a loop closure we perform ICP between the current scan and laser
  # scans captured from nearby poses. In order to be considered a loop closure,
  # the ICP "fitness score" must be less than this number.
  max_tolerable_fitness: 0.05

  # Don't attempt loop closures with poses in the graph that were collected within
  # this translational distance (m) from the current pose.
  distance_to_skip_recent_poses: 10 #10 # 200

  # If a loop has recently been closed, don't close a new one for at least this
  # amount of translational distance (m).
  distance_before_reclosing: 5 #10

  # if a loop closure is found but the angle is larger than this, reject it
  max_rotation_deg: 50

  # If a batchloop has recently been closed, don't close a new one for at least this
  # amount of translational distance (m).
  distance_before_batch_reclosing: 10 #3


  #--------------------------------------------------------------------------------
  # ICP Settings for laser loop closure
  #--------------------------------------------------------------------------------

  icp_lc:
    # Stop ICP if the transformation from the last iteration was this small.
    tf_epsilon: 0.0000000001

    # During ICP, two points won't be considered a correspondence if they are at
    # least this far from one another.
    corr_dist: 0.3

    # Iterate ICP this many times.
    # Check this
    iterations: 5 # Default from original branch is 20: 
    
    # Number of threads for multithreaded GICP
    threads: 2

  #--------------------------------------------------------------------------------
  # SAC-IA Settings for feature-based initialization
  #--------------------------------------------------------------------------------

  sac_ia:
    # Iterate SAC-IA this many times.
    iterations: 100

    # Number of previous scans to accumulate for target pointcloud
    # 0 means no accumulation
    num_prev_scans: 1
    num_next_scans: 0
    
    # Radii of area to consider when computing normals and features
    normals_radius: 1.0
    features_radius: 2.0

    # If SAC fitness score is more than the following value, it will be rejected
    fitness_score_threshold: 0.30


  harris3D:
    harris_threshold_: 0.000000005
    harris_suppression: true
    harris_radius: 0.1
    harris_refine: false
    harris_response: 1