########################################
# PARAMETERS FOR UWB
########################################

# Flag to activate UWB data outlier rejection
b_use_uwb_outlier_rejection: true

# Flag to decide whether to show uwb data or not (for debugging)
b_use_display_uwb_data: false

# UWB range measurement noise (standard deviation)
uwb_range_measurement_error: 2.0

# Selection of UWB range measurement compensation
# 0 - No compensation
# 1 - TODO
uwb_range_compensation: 0

# Optimizer selection for UWB factors: 0 - ISAM2, 1 - LM
uwb_factor_optimizer: 1

# Number of range measurement which is necessary to add a new UWB factor
uwb_skip_measurement_number: 5

# Pose key number for checking whether there are enough number of range measurements or not
uwb_update_key_number: 2

# Rquired number of pose keys linked with UWB range measurement
uwb_required_key_number_first: 3
uwb_required_key_number_not_first: 1

# Number of range factors added at the first observation
uwb_number_added_rangefactor_first: 3

# Number of range factors added aganst an existing UWB key in the pose graph
uwb_number_added_rangefactor_not_first: 1

# Range added into the pose graph should be longer than the following value
uwb_minimum_range_threshold: 3.0

# Pose key number threshold to wait for accepting UWB signal
uwb_first_key_threshold: 3
