#Load AprilTag GT coordinates
calibration_left_x: -0.005
calibration_left_y: 0.0
calibration_left_z: 0.605

calibration_right_x: -0.005
calibration_right_y: 0.0
calibration_right_z: 0.281

distal_x: 11.3
distal_y: 0
distal_z: 0.15